### ISSUE TITLE
Update the Dockerfiles

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/refimpl#177]
Tomcat configs use JDK 8, which should no longer work with Lyo 5. I would suggest to 

- [x] Switch from `tomcat:9-jdk8-corretto` to `tomcat:9-jdk11-temurin` as per https://hub.docker.com/_/tomcat . (done in #180)
- [x] Switch from `jetty:10-jdk11-eclipse-temurin` to `jetty:10-jdk17-eclipse-temurin` such as to prepare for dropping JDK 11 (done in https://github.com/oslc-op/refimpl/commit/0f2ab0524df97f87147fefb61b4c6b33f79883f1)

We also have the Tomcat config only for RM and the default Docker Compose does not use it:

- [ ] Replicate the Tomcat dockerfile to all 4 OSLC servers.
- [x] Add a new `docker-compose.tomcat.yml` that would add non-default `.build.dockerfile` values (see [docs](https://docs.docker.com/compose/compose-file/build/#illustrative-example)) (done in #180)

Ideally,

- [x] Add/duplicate or matrixify a CI config to test with Tomcat as well (done in #180)
- [ ] Downgrade Docker Compose v3 files to Docker Compose v2 to allow setting CPU/RAM limits w/o hacks (see [discussion](https://github.com/docker/compose/issues/4513#issuecomment-327159797)). This is mostly relevant for a demo instance deployment on the server.

**Comment by berezovskyi** [comment]
@jadelkhoury don't have time for this now but saw this problem after being reminded by Andy Seaborne's email and wrote it down. Could you take a look at this when you have time?

**Comment by Jad-el-khoury** [comment]
Yes. I can look into it.

**Comment by berezovskyi** [comment]
fixed in #317
